name:                combine-align
version:             0.1.0.0
github:              "jlavele/combine-align"
license:             MIT
author:              "John C. Lavelle"
maintainer:          "example@example.com"
copyright:           "2019 John C. Lavelle"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/jlavelle/combine-align#readme>

dependencies:
- base >= 4.7 && < 5
- semialign
- semigroupoids
- hedgehog
- witherable
- these
- containers

library:
  source-dirs: src

executables:
  combine-align-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - combine-align

tests:
  combine-align-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - combine-align
